export const FORM_FIELD_CHANGED = 'FORM_FIELD_CHANGED';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SET_FORM_MODE = 'SET_FORM_MODE';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const AUTH_FORM_SUBMITTED = 'AUTH_FORM_SUBMITTED';

